name: 'Deploy Docker Images'
description: 'Deploy Docker images to specified environment'

inputs:
  environment:
    description: 'Target environment (acceptance, qa, production)'
    required: true
  version:
    description: 'Version tag to deploy'
    required: true
  image-urls:
    description: 'JSON array of image URLs with digests or tags'
    required: true
  ssh-host:
    description: 'SSH host to deploy to'
    required: true
  ssh-user:
    description: 'SSH user'
    required: true
  ssh-key:
    description: 'SSH private key'
    required: true
  github-token:
    description: 'GitHub token for GHCR authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse Image URLs
      id: parse
      shell: bash
      run: |
        echo "Parsing image URLs for deployment"
        IMAGE_URL=$(echo '${{ inputs.image-urls }}' | jq -r '.[0]')
        echo "image-url=$IMAGE_URL" >> $GITHUB_OUTPUT
        echo "Deploying: $IMAGE_URL"

    - name: Deploy to Server
      shell: bash
      run: |
        set -e
        
        SSH_HOST="${{ inputs.ssh-host }}"
        SSH_USER="${{ inputs.ssh-user }}"
        IMAGE_URL="${{ steps.parse.outputs.image-url }}"
        VERSION="${{ inputs.version }}"
        ENVIRONMENT="${{ inputs.environment }}"
        
        echo "🚀 Deploying to $ENVIRONMENT environment"
        echo "📦 Host: $SSH_HOST"
        echo "👤 User: $SSH_USER"
        echo "🐳 Image: $IMAGE_URL"
        echo "🏷️  Version: $VERSION"
        
        # Create SSH key file
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-key }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Add host to known_hosts
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts 2>/dev/null || true
        
        # Create deployment script
        cat > /tmp/deploy.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo "🚀 Starting deployment to ${ENVIRONMENT}"
        echo "📦 Image: ${IMAGE_URL}"
        echo "🏷️  Version: ${VERSION}"
        
        # Login to GHCR
        echo "${GITHUB_TOKEN}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
        
        # Pull new image
        echo "⬇️  Pulling image..."
        docker pull ${IMAGE_URL}
        
        # Stop existing container
        echo "🛑 Stopping existing container..."
        docker stop monolith-app 2>/dev/null || true
        docker rm monolith-app 2>/dev/null || true
        
        # Run new container
        echo "▶️  Starting new container..."
        docker run -d \
          --name monolith-app \
          --restart unless-stopped \
          -p 3000:3000 \
          -e NODE_ENV=production \
          -e APP_VERSION=${VERSION} \
          ${IMAGE_URL}
        
        # Wait for application to start
        echo "⏳ Waiting for application to start..."
        sleep 10
        
        # Verify deployment with health check
        echo "🏥 Running health check..."
        MAX_ATTEMPTS=30
        ATTEMPT=0
        
        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          if curl -f http://localhost:3000/health 2>/dev/null; then
            echo "✅ Health check passed!"
            echo "✅ Deployment successful!"
            
            # Show container status
            echo ""
            echo "📊 Container status:"
            docker ps --filter name=monolith-app
            
            # Cleanup old images
            echo ""
            echo "🧹 Cleaning up old images..."
            docker image prune -af --filter "until=24h" || true
            
            echo ""
            echo "🎉 Deployment complete!"
            exit 0
          fi
          
          ATTEMPT=$((ATTEMPT + 1))
          echo "⏳ Waiting for health check... attempt $ATTEMPT/$MAX_ATTEMPTS"
          sleep 2
        done
        
        echo "❌ Health check failed after $MAX_ATTEMPTS attempts"
        echo "📋 Container logs:"
        docker logs monolith-app
        exit 1
        EOF
        
        # Make script executable
        chmod +x /tmp/deploy.sh
        
        # Copy deployment script to server
        echo "📤 Copying deployment script to server..."
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no /tmp/deploy.sh ${SSH_USER}@${SSH_HOST}:/tmp/
        
        # Execute deployment script on server
        echo "🚀 Executing deployment on server..."
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} \
          "export ENVIRONMENT='${ENVIRONMENT}' \
           IMAGE_URL='${IMAGE_URL}' \
           VERSION='${VERSION}' \
           GITHUB_TOKEN='${{ inputs.github-token }}' \
           GITHUB_ACTOR='${{ github.actor }}' && \
           bash /tmp/deploy.sh"
        
        # Cleanup
        rm -f ~/.ssh/deploy_key /tmp/deploy.sh
        
        echo "✅ Deployment to ${ENVIRONMENT} completed successfully!"
